### ISSUE TITLE
Passing spark-defaults.conf values as part of spring cloud task modules

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-task-app-starters/spark-yarn#1]
_From @sabbyanandan on May 6, 2016 22:34_

_From @rejurs on April 29, 2016 20:9_

Hi Team,

Could you please help me to pass the spark-defaults.conf values when we are running **java -jar sparkapp-yarn/target/sparkapp-yarn-task-1.0.0.BUILD-SNAPSHOT-exec.jar**. 

_Copied from original issue: spring-cloud/spring-cloud-task-modules#36_

_Copied from original issue: spring-cloud/spring-cloud-task-app-starters#18_

**Comment by sabbyanandan** [comment]
_From @rejurs on May 9, 2016 14:28_

@sabbyanandan : Is this resolved? / Is there any timeline ? / Ami I making any mistake? Could you please update me.

**Comment by sabbyanandan** [comment]
@trisberg Didn't we verify this on Bacon release? Can we close it?

**Comment by trisberg** [comment]
Not enough information to go by. Please create a new issue with configuration details and stacktrace if this is still an issue.
