### ISSUE TITLE
Unrecognized option error when launching spring-cloud-starter-task-spark-yarn-1.2.0.RELEASE 

### ISSUE THREAD

**Issue by GlebMendrul** [spring-cloud-task-app-starters/spark-yarn#6]
Hi, I'm running spring-cloud-dataflow-server-yarn-1.2.0.RELEASE server in docker cloudera container with SPARK2-2.1.0.cloudera1-1.cdh5.7.0.p0.120904-el6.parcel and hadoop-2.6.0-cdh5.11.1.
  
Server starts without any issues, but when I'am submitting spark task it fails with:
`Unrecognized option: --spark.app-jar=hdfs://app/spark/basic-spark-0.1-SNAPSHOT-jar-with-dependencies.jar
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.`

I'm registering app and creating task using:

`app register --type task --name spark-yarn --uri hdfs:///app/spark/spring-cloud-starter-task-spark-yarn-1.2.0.RELEASE.jar` 

`task create spark --definition  "spark-yarn --spark.app-name=my-test-pi --spark.app-class=app.SparkESIngester --spark.app-jar=hdfs://app/spark/basic-spark-0.1-SNAPSHOT-jar-with-dependencies.jar --sark.assembly-jar=hdfs://app/spark/spark-assembly-1.6.1-hadoop2.6.0.jar --spark.app-args=10"`

`task launch spark`

If anyone is able to provide some assistance would me immensely appreciated, as nothing on the web makes sense to resolve this and get the spark task going!!!

Thank you!

**Comment by sabbyanandan** [comment]
HI, @mglebka: While we wait for someone to look at it closely, I wanted to point out that you have a typo in the stream definition. `--sark.assembly-jar` should be `--spark.assembly-jar` - worth retrying it with the right property.

**Comment by GlebMendrul** [comment]
Hi @sabbyanandan, thank you for quick feedback, I fixed this typo but it did not help, still the same issue.

**Comment by GlebMendrul** [comment]
Hi, the problem was that I was using **spring-cloud-starter-task-spark-yarn.jar** instead of **spark-yarn-task.jar**. Closing this issue.
